Hardware limits
Programming-TRIGON/TRIGONLib pull request #1
Opened 2024-08-08 15:44 UTC by Strflightmight09

2024-08-08 15:52 UTC, Nummun14 approved these changes

2024-08-08 16:01 UTC, Nummun14 requested changes

2024-08-08 16:01 UTC, Nummun14 commented on src/main/java/org/trigon/hardware/phoenix6/talonfx/TalonFXSignal.java
> +    MOTOR_VOLTAGE(TalonFX::getMotorVoltage),
make this more skibidi

2024-08-08 16:01 UTC, strflightmight approved these changes

2024-08-10 20:24 UTC, levyishai approved these changes

2024-08-10 20:25 UTC, merged